version: "3"

networks:
  app-tier:
    driver: bridge
  grafana-tier:
    driver: bridge

services:
  backend:
    container_name: moduel_web
    build: ./back/django
#    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver
    volumes:
      - ./back/django:/code
    networks:
      - app-tier
    expose:
      - "8000"
    ports:
      - "8000:8000"

  mysql_db:
    image: mysql:latest
    networks:
      - app-tier
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - "3307:3306"
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: modeul
      MYSQL_USER: modeul
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: rootpassword
